---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, on-prem' 
summary: 了解内部 ONTAP 集群的新增功能。 
---
= 内部 ONTAP 集群的新增功能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解内部 ONTAP 集群的新增功能。



== 2022 年 2 月 27 日



=== 数字电子邮件中提供了一个 " 内部部署 ONTAP " 选项卡。

现在，您可以查看内部 ONTAP 集群的清单及其硬件和服务合同到期日期。此外，我们还提供了有关这些集群的其他详细信息。

https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html#viewing-cluster-information-and-contract-details["请参见如何查看此重要的内部集群信息"]。您需要为集群创建一个 NetApp 支持站点帐户（ NSS ），并且需要将 NSS 凭据附加到您的 Cloud Manager 帐户。



== 2022 年 1 月 11 日



=== 您添加到内部 ONTAP 集群上的卷的标记可以与标记服务结合使用。

添加到卷的标记现在与应用程序模板服务的标记功能相关联，该功能有助于您组织和简化资源管理。



== 2021 年 11 月 28 日



=== 已简化内部 ONTAP 集群的创建卷向导

我们重新设计了创建卷向导，以便于使用，现在您可以选择自定义导出策略。



== 2021 年 3 月 8 日



=== Active IQ 服务中提供的内部 ONTAP 集群信息

* 当 Active IQ 显示内部集群列表（基于您的 NSS 帐户）时，您可以单击按钮 link:task-discovering-ontap.html#discovering-clusters-from-the-discovery-page["发现集群"^] 并将其添加到 Cloud Manager Canvas 。这样可以更轻松地从 Cloud Manager 管理所有存储系统。
* 当 Active IQ 确定一个或多个集群需要更新固件时，您可以单击按钮以 link:task-managing-ontap.html#downloading-new-disk-and-shelf-firmware["下载 Ansible 攻略手册并升级集群固件"^]。
* 新的 link:task-managing-ontap.html#viewing-on-prem-workloads-that-are-candidates-for-the-cloud["云就绪工作负载选项卡"^] 提供我们确定最适合从内部 ONTAP 集群迁移到云的工作负载或卷列表。移动其中一些卷可以降低成本，提高性能和故障恢复能力。
+
请参见 link:https://www.netapp.com/knowledge-center/what-is-lift-and-shift["什么是升降和移动？"]


